### ISSUE TITLE
Item rolling - doesn't roll on items at all sometimes

### ISSUE THREAD

**Issue by Marsbars** [Marsbars/DungeonCrawler-Issues#1]
Sometimes the bot doesn't roll on items at all - I think this happens when it CAN need on it but when getting stat values somethings breaks...

**Comment by Kamogli** [comment]
What I observed on my first run - it DOES greed on certain items, but won't confirm the "It'll be bound to you after pickup" pop-up. If you confirm this pop-up manually, it greeds just fine

**Comment by michalrozek90** [comment]
I noticed that all needs was good for me and most of the rest items was greeded too but sometimes it happens that the bot is doing nothing. I am sure that 2 items was from the trash mobs (1 which should be needed).

**Comment by Marsbars** [comment]
Found another issue on this but have since fixed it - will be in next release
