### ISSUE TITLE
No ress from other party members

### ISSUE THREAD

**Issue by michalrozek90** [Marsbars/DungeonCrawler-Issues#10]
Hello,
It can happen that sometimes the bot will die (pulling some unwanted mobs or even other way) and the other party members won't want to resurrect you even though they can.

The question is what next ? For now I have only one thought: Bot shouldn't wait for a ress forever so after some time it should release the body. 

What he should do after release or (if death run will be avaible) after entering the instance - I don't know but I would like to start a discussion :)

**Comment by Marsbars** [comment]
A possible solution would be to follow a dungeon route until close enough to the party, then return to following.
This is obviously a while away as I need to do Tanking routes first.
Other suggestions welcome

**Comment by Marsbars** [comment]
For now the issue is fixed however a different issue was introduced where the tank waits for party members outside of objectmanager range even though they are further ahead in the dungeon
