### ISSUE TITLE
auto disable close on teleport

### ISSUE THREAD

**Issue by Marsbars** [Marsbars/DungeonCrawler-Issues#17]

**Comment by michalrozek90** [comment]
Also "start fight with elite" & "can attack unit already in combat" should be enabled I think :)

**Comment by Marsbars** [comment]
I think those 2 are only considered if wrobots states are doing the targetting, since I have my own they shouldn't matter. I have not had to set these 2 settings on any of my tests

**Comment by Marsbars** [comment]
added disabling close on teleport
