### ISSUE TITLE
Force regen state to finish

### ISSUE THREAD

**Issue by Kamogli** [Marsbars/DungeonCrawler-Issues#26]
Howdy Mars,

something that came up after extensive testing sessions while you were away was: Healers and Mana Classes in general rebuff / heal while in regen state. They'll burn very quickly through their drinks doing this - starting to drink, standing up to rebuff / heal, drink again. 

Is it possible for dungeon crawler to enforce regen state to finish maybe? 

Cheers, welcome back,

Kamo

**Comment by Marsbars** [comment]
No, this would be handled by the fightclass - the fightclass shouldn't cast if regging. Would need to be built into AIO

**Comment by Kamogli** [comment]
aight, makes sense, will check back with Tala on this. Cheers!!

Am Di., 18. Feb. 2020 um 12:49 Uhr schrieb Maurice <notifications@github.com
