### ISSUE TITLE
Release body sometimes not working at all

### ISSUE THREAD

**Issue by michalrozek90** [Marsbars/DungeonCrawler-Issues#29]
We observed that sometimes bots are not releasing the body. After manually click on pop up window to release they are not doing anything (no death run, nothing).

**Comment by michalrozek90** [comment]
Maybe it's because the dungeon dont have a death run included and that's why the bot is not releasing ? You closed one thread about this before and maybe it has something to do with that :)

**Comment by Marsbars** [comment]
Fixed by handling events in separate thread
