### ISSUE TITLE
Leaves dungeon too early after dungeon reward is received

### ISSUE THREAD

**Issue by Marsbars** [Marsbars/DungeonCrawler-Issues#3]
Leaves dungeon too early after dungeon reward is received - this is because it's currently on a timer.
What would be better if it first checks to see if all the loot rolls have finished and then leaves.

**Comment by michalrozek90** [comment]
I think that if the bot choose between need&greed and then leave the instance it will be not a problem because the won item should appear in eq anyway but only after all players will make their choices too.
