### ISSUE TITLE
Aggro fest

### ISSUE THREAD

**Issue by olizmo** [Marsbars/DungeonCrawler-Issues#6]
Did a run of BRD with dCrawler on my rogue, i had to leave the group because of my bot just targeting ranged mobs far away and throught that aggroed everything, several times.

**Comment by Kamogli** [comment]
BRD torch room that was, right? That one is a bitch for sure

**Comment by olizmo** [comment]
> BRD torch room that was, right? That one is a bitch for sure

Yes exactly! But i see this situation all the time in ''party bot'' aswell.

**Comment by Marsbars** [comment]
The way the targetting works is it will target the tanks target and start a fight with it. Maybe i need to add something for melees to only start fights with mobs the tank is targetting AND they're within melee range of the tank?

**Comment by olizmo** [comment]
YES! That would be a great start, even something for ranged!

**Comment by Marsbars** [comment]
True that would actually make sense for ranged as well, I'll make the change.
