### ISSUE TITLE
Feature: Wait for resurrection 

### ISSUE THREAD

**Issue by Kamogli** [Marsbars/DungeonCrawler-Issues#7]
At least until walk to rez is finished: An option for a dead toon to not resurrect manually but to wait for rez by partymember and auto-accept it then :-)

**Comment by Marsbars** [comment]
This should already be the case IF a party member that can rezz is alive.
Or are you saying if the group wipes also don't release?

**Comment by Kamogli** [comment]
Should have been clearer, sorry - exactly: I think it shouldn't rez in any case until there is no walk to rez. Just died in a group with a Shaman who was alive, dCrawler still did the rez. Does it have some kind of range check, where it'll only wait for rez, if the Healer is in a certain range?

**Comment by Marsbars** [comment]
hmm, no not range but it does check if the unit is valid, could he have ran out of the dungeon or ported out?

**Comment by Kamogli** [comment]
will observe the rez behavior and report back in case it happens again. Sadly wasn't there to see it, just came back when toon was already in rez mode

**Comment by Marsbars** [comment]
Added not releasing if dungeon does not have a deathrun vector
